// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DragController from "./drag_controller.js"
application.register("drag", DragController)

import DragTeamsController from "./drag_teams_controller.js"
application.register("drag-teams", DragTeamsController)

import FileUploadController from "./file_upload_controller.js"
application.register("file-upload", FileUploadController)

import ParticipantCompleteController from "./participant_complete_controller.js"
application.register("participant-complete", ParticipantCompleteController)

