// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ParticipantCompleteController from "./participant_complete_controller.js"
application.register("participant-complete", ParticipantCompleteController)
