inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Customizations for PiKaichu project
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/cache_schema.rb'
    - 'db/queue_schema.rb'
    - 'db/cable_schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Allow longer lines for legacy code (omakase default is 120)
Layout/LineLength:
  Max: 150

# Allow longer methods for complex state machine logic  
Metrics/MethodLength:
  Max: 50

# Allow longer classes for complex models
Metrics/ClassLength:
  Max: 250
